spring:
  application:
    name: appNews
  datasource:
    url: jdbc:h2:mem:testdb
    username: bd
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}

upload:
  path: ./upload

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  packages-to-scan: com.news.news
  paths-to-match: /**
